version: '3.7'

services:
  database:
    container_name: ecst-mysql
    image: mysql:8.0.12
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
  
  httpd:
    container_name: ecst-apache-php
    build: ./docker
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
    links:
      - database