FROM php:7.2.10-apache

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN a2enmod rewrite

RUN apt-get update &&\
    apt-get install --no-install-recommends --assume-yes --quiet ca-certificates \
    curl \
    git \
    && docker-php-ext-install -j$(nproc) \
    pdo_mysql \